### Register Route

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "alsheha88",
    "password": "hgadpmurt",
    "firstName": "Abdulaziz",
    "lastName": "Alsheeha"
}

### Login Route

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "alsheha88",
    "password": "hgadpmurt"
}

### Get All Bookmarks
GET http://localhost:3000/bookmarks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc3NjM1MDcwLCJleHAiOjE3Nzc3MjE0NzB9.6qeAxeCHJy-bua6uQCB0mOOYfui6hBEY6dutTlxZLM0

### Bookmarks POST Request
POST http://localhost:3000/bookmarks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc3NjM1MDcwLCJleHAiOjE3Nzc3MjE0NzB9.6qeAxeCHJy-bua6uQCB0mOOYfui6hBEY6dutTlxZLM0
Content-Type: application/json

{
    "title": "Prisma",
    "url": "https://prisma.org",
    "description": "Prsima ORM for object relations mapping",
    "tags": ["CSS", "JS", "HTML"]
}